# Generated by Django 4.2.3 on 2024-05-13 14:41

from django.db import migrations, models
import django.db.models.deletion
import projects.validators


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            projects.validators.validate_not_empty,
                            projects.validators.validate_max_length,
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        max_length=500,
                        validators=[
                            projects.validators.validate_not_empty,
                            projects.validators.validate_max_length,
                        ],
                    ),
                ),
                (
                    "github_url",
                    models.URLField(
                        validators=[
                            projects.validators.validate_not_empty,
                            projects.validators.validate_max_length,
                        ]
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        max_length=50,
                        validators=[
                            projects.validators.validate_not_empty,
                            projects.validators.validate_max_length,
                        ],
                    ),
                ),
                (
                    "key_skill",
                    models.CharField(
                        max_length=50,
                        validators=[
                            projects.validators.validate_not_empty,
                            projects.validators.validate_max_length,
                        ],
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="projects.profile",
                    ),
                ),
            ],
        ),
    ]
